### ISSUE TITLE
Lint Codebase

### ISSUE THREAD

**Issue by b5** [qri-io/2017-frontend#12]
Need to get everything in /src/js linted. directories that need linting:

* [x] src/js/actions
* [x] src/js/components
* [x] src/js/containers
* [x] src/js/middleware
* [x] src/js/propTypes
* [x] src/js/reducers
* [x] src/js/selectors
* [x] src/js/store
* [x] src/js/utils
* [x] src/js/validators

**Comment by ramfox** [comment]
Closed by #34
