### ISSUE TITLE
reload button for datasets

### ISSUE THREAD

**Issue by ramfox** [qri-io/2017-frontend#124]
When there is an error loading datasets, lets the user retry manually via a button that calls to loadDatasets

**Comment by osterbit** [comment]
- if either `$(QRI_PATH)/peers.json.lock` or `$(IPFS_PATH)/repo.lock` files exist when I launch qri (which will happen if you are moving between the cli and gui and haven't properly closed the other out or if either doesn't gracefully shut down), I get the following: 
![image](https://user-images.githubusercontent.com/3967296/40386246-2956e968-5dd7-11e8-925d-eb146287b260.png)
but the `reload datasets` button doesn't do anything currently

- additionally even if I delete those lock files, once I get in this state, I am (so far) unable to get back to an 'uncorrupted' state without completely erasing my profile
