### ISSUE TITLE
User Help

### ISSUE THREAD

**Issue by b5** [qri-io/2017-frontend#136]
From Tom:
> I see no datasets on first load, it’d be nice to have an initial set of datasets, and a query prewritten. I’m looking for instructions on how to interact with the platform, it should show you how to use it in some way.Maybe it has a help menu that’s connected to the documentation?

Generally, we need a more accessible way for users to get help within the app. I see two options here:

1.Focus on building a solid static documentation site, and providing links within the app to documentation
2. Focus on bringing help within the app itself.

The former can lead to a cleaner reading experience, the latter is easier to keep in sync with the code itself.

**Comment by ramfox** [comment]
We are doing this! We now have a 'help' link to the app that sends the user to our website full of documentation. It's by not means finished, but I don't think we need a general issue saying we need user help any longer, since documentation is now part of our iteration process.
