### ISSUE TITLE
Show size of datasets, like, everywhere.

### ISSUE THREAD

**Issue by b5** [qri-io/2017-frontend#141]
I think a general summary of number of rows, columns, and byte count that uses "social media counter conventions" would be a very good idea. By counter conventions I mean rounding by order-of-magnitude for brevity. Examples:

* 234 rows, 16 columns, 4mb
* 4k rows, 634 columns, 1.1Gb
* 3M rows, 3 columns, 200Gb

It'd be great to display these stats in more places.

**Comment by ramfox** [comment]
We do this!!! yay!

We currently show # of rows, fields, and size of dataset.

Closing
