### ISSUE TITLE
Main screen is blank

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#151]
I closed out and logged back into the app.  Was able to hover over and click icons of the LHS panel, but the main field remained completely blank.

**Comment by ramfox** [comment]
Hi rico!!! By 'closed out' you mean you quit from the top menu?

When you launched the app again, did it show the 'Welcome to Qri' loading message? Or just nothing?

I'm assuming this was the packaged version of the app?

Also, have you been able to open it successfully since?

**Comment by b5** [comment]
I'ma close this due to age 🕺
