### ISSUE TITLE
feature request: github-style markdown rendering for dataset description?

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#176]
and maybe more generally, treating all text-box input as renderable markdown?   github's markdown-to-html converter is publically available ([github.com/github/markup](https://github.com/github/markup)) though unfortunately in ruby, but looks like there are off-the-shelf options in golang ([github.com/golang-commonmark/markdown](https://github.com/golang-commonmark/markdown)) and javascript ([github.com/showdownjs/showdown](https://github.com/showdownjs/showdown)) as well.  obviously not super important but have been thinking the dataset description page reading like a github README.md would help with readability espececially for more complex datasets

**Comment by ramfox** [comment]
newest refactor/mockups show dataset meta, structure, etc summaries in a more coherent way, on the `overview` page, that is trying to bridge the gap between the full dataset and what is useful to know when you are trying to learn about a dataset. closing this issue for now.
