### ISSUE TITLE
proposal: lower contrast and/or different color gridlines for selected cells

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#217]
I think the contrast level for the *unselected cells looks really good/maybe good reference point?

![image](https://user-images.githubusercontent.com/3967296/33911174-753343a0-df5f-11e7-81b6-155774b33a9f.png)

**Comment by b5** [comment]
agreed, it'd be nicer to have those grid lines knocked back a bit, @osterbit feel like getting your hands dirty on frontend style tweaking? I'd love a tiny PR that changes just this. best place to start editing is likely [here](https://github.com/qri-io/frontend/blob/master/lib/scss/_handsontable.scss#L298)

**Comment by ramfox** [comment]
Closed due to changed color scheme
