### ISSUE TITLE
Add Datasets from "main page"

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#220]
Would be nice to be able "Add" dataset directly from my personal page (home). More intuitive to add a dataset to my node while i'm checking in on my node page than when I'm on a generic datasets page

This may effectively kill the entire datasets module or orient it to become purely about discovery

**Comment by ramfox** [comment]
Hey! You mean, 'add' as in upload a file or add from a url?

Or add a peer's dataset?

`:)`

**Comment by ramfox** [comment]
k, after talking to rico he is recommending we add an 'add' button on Profile page

**Comment by ramfox** [comment]
All dataset creation happens in the editor.
