### ISSUE TITLE
"Profile Page" enhancements

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#224]
1) Add some structure to bio section so viewer can understand... 

(e.g. Twitter: @rgardaphe since "atting" someone could refer to their IG handle.)

2) As a user, I WANT to add my email address to get qri updates or whatever, but I DO NOT want random peers to see my email. Have default on settings page for email to be set to private, consider allowing user to change to public

**Comment by ramfox** [comment]
Added part 2 to separate issue #230
