### ISSUE TITLE
feat: ship a bare-bones 0.1.0 webapp frontend

### ISSUE THREAD

**Issue by b5** [qri-io/2017-frontend#242]
I can remember the first time I engaged with git, it was so I could join GitHub. My post-CVS, never-ever-touched-SVN understanding of version control is intrinsically tied to a friendly user interface. I think we need to do the same thing to our frontend that we did to the backend, strip down to a bare minimum feature set & ship, so we can all have an interface that allows us to see the value of this distributed network of data.

So with that I'm adapting what the 0.1.0 release of our frontend will be. We're going to scale waaaaay back, and slowly re-add features over time.

### Remove:
* Electron app support for now. We'll restore our desktop app once we've had a chance to stabilize, I'm guessing on version 0.3.0 or later of the frontend.
* All data viewing. Frontend should only be able to view dataset metadata & history for now
* All SQL support
* Schema Display. This one hurts, but we'll restore it asap.

### Add:
* Local Webapp. frontend should build & run as a compiled redux binary
* Serve app package over IPFS.
* Support for our new 0.1.0 JSON API
* Update Color Palette to match our new branding (grey, white, blobs)

-- --
### Steps to complete:
_(this is a self-assigned issue, so I'm keeping this fairly broad. Steps to complete should be more detailed than this)_
* [x] finish & merge fix/build branch
* [x] write a webpack config file for webapp development
* [x] cut a new set of sketch files that updates our branding
* [x] remove the stuff that should be removed
* [x] update API endpoints & actions to match
* [ ] match app to sketch files
* [ ] write a webpack build process for web
* [ ] ship that shit
* [ ] PR this feat into qri-io/qri as part of `qri connect` command, with an optional flag to disable the webapp

**Comment by ramfox** [comment]
Features that work:
* Datasets (homepage)
* Dataset
* MetadataEditor
* Rename dataset
* export dataset
* Settings/update profile (but profile is not correctly displayed)

Features that don't work:
* Profile (hand in hand with peerpage)
* Peer page
* Peers
* Commit page (Dataset page at a certain commit)
* Add dataset
* sidebar stats are not real

So are there any of these features we want to make sure to include, or do we just turn them all off?

**Comment by ramfox** [comment]
As per our conversation:

remove:
Peers, Peer, Profile, Settings
And anything that doesn't help Datasets, or Dataset function.

Leave in charts, and anything that touches displaying data
