### ISSUE TITLE
Deleting a local model

### ISSUE THREAD

**Issue by ramfox** [qri-io/2017-frontend#249]
@b5 could use some help

Right now:

https://github.com/qri-io/frontend/blob/a03e564b13327f491163315adb26423cc5a43cea/lib/middleware/locals.js#L38-L52

The `CLEAR_MODEL` case is commented out.

I tried my best to get it to work, haha.
I learned:
schema.getKey() isn't a function. Looks like schema.Key is what we are looking for here

`next(actionWith({ locals: { [schema.key]: { [id] : undefined }}}))`
is what i tried

But it didn't seems to... do anything?

I've googled around to see how to remove entities using normalizr, and maybe it's not really a thing people do?

Anyway, this relates to editing metadata, we create a local copy of a dataset, and use that copy to change the metadata. I want to remove this copy once we have sent the metadata off. It's honestly not breaking anything right now, but I can see maybe a time where it is out of sync with the actual data in a way that breaks something.

**Comment by b5** [comment]
seems we've refactored past the need to restore `CLEAR_MODEL`, given that our locals reducer now looks like this:

https://github.com/qri-io/frontend/blob/17aa8e8c8b5263b4845f3da99274e8f9416e6e2e/lib/reducers/locals.js#L19

Is this closable @ramfox?
