### ISSUE TITLE
Dataset Access Control Options

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#261]
We'll need a deep discussion on how we understand and present the options for datasets to be stored within sub-groups, leveraging industry best practices

Data.world: Slider for open (public) or private (viewable to those i invite)

Google Sheets: "Those with access...
  - Can edit
  - Can comment
  - Can view"

Admin Rights
  - Can add other admins?
  - Can transfer ownership (rights to delete)

"Tools for communities to self-govern" -- need to agree on some basic principles vs. flexibility for communities to design on their own. "Github Circle"
  - Forking
  - Request Change
  - Auto submit to ______ when PR is written
  - Accept
  - Merge

**Comment by ramfox** [comment]
We do need a deep discussion on how we understand datasets and permissions, but for now, datasets are unlisted, with an option to be published. Let's close this issue until we are at a place to talk about datasets, 'ownership', and private vs public data
