### ISSUE TITLE
overhaul scss directory, removing bootstrap

### ISSUE THREAD

**Issue by b5** [qri-io/2017-frontend#290]
### Problem
For a while we've been working with a bloated global stylesheet built on top of bootstrap. Because we've deviated a little too far from bootstrap's conventions, it's difficult to make a change to any of our global `scss` stylesheets, so I think it's time for an overhaul that removes bootstrap in favor of our own conventions.

### Files we should keep
* normalize.scs and/or reboot (these should just be copied into one file for now)
* site.scss
* variables.scss
* type.scss
* forms.scss - _let's audit this one for interaction with other bootstrap files_

### Files we should *mostly* delete
* there's a few things in buttons: `btn, btn-primary, btn-large`, etc. let's keep those
* modal

**Comment by ramfox** [comment]
In our conversation in person, we mentioned (I believe) removing mixins.

Now that I have a better understanding of what it's doing, I think leaving a certain mixins for certain sections of the scss is the way to go. Def learning alot, v excited to have an excuse to dive into this.
