### ISSUE TITLE
Datasets component should wait for a populated session profile before calling loadDatasets

### ISSUE THREAD

**Issue by b5** [qri-io/2017-frontend#302]
In a recent change I moved a call to `this.props.loadSessionProfile` in the `App` component from `componentWillMount` to a check in `componentWillReceiveProps`. This is more correct, as the first call to loadSessionProfile _must happen after we know the api is working_.

This unearthed a new problem, some container-components rely on session data being set before they are ever mounted, which is causing the following sequence of events:
1. App container boots in "loading mode", firing off calls to api status.
2. API responds "OK I exist", causes a re-render
3. App container picks up this change in `componentWillReceiveProps`, fires off a request for the session profile. Since the app is no longer loading, it renders the `children` component, which in this case is a `DatasetContainer`
4. `DatasetContainer` mounts and immediately fires of a request to list datasets, using the session profile endpoint, _but doesn't have session profile data, so this request goes to the wrong place_, causing the request to fail.
5. The request for SessionProfile app kicked off completes, so now we have a proper session.
6. If the user clicks "reload datasets" it'll work this time, because `DatasetContainer` now has a proper SessionProfile.

Phew. So to fix this, *we need to defensively code all of our Containers to wait for a session profile*, starting with DatasetContainer. This amounts to only calling `this.loadDatasets` in `DatasetContainer.componentWillMount` if we have a session profile, and _also_ check for changes to sessionProfile in `componentWillReceiveProps`.

There is another way we can defend against this, and that's with the `/me` endpoint in the API. This is exact reason for having `/me` endpoint, which is to remove the need for any session-specific information to get session user data. To make this work better on the frontend we should adjust any session-dependent actions to call to `/me` instead of the more general `/[profileID]/endpoint`.

This last part will take longer to get right, as we need to put work into our API to make sure all these session-dependant requests have a corresponding endpoint under the `/me` path.

**Comment by ramfox** [comment]
Okay cool.

So I'm assuming you mean `DatasetsContainer` not `DatasetContainer`.

When you grab the session from the server, you are hitting the `/me` endpoint. We could add a `loadSessionDatasets` action that pulls the session's datasets from the `/list/me` endpoint.


How each container deals with having no session id:
* AddDataset (right now returned the 'Read Only' page if there is no session id)
* Datasets (adding the defensive changes now)
* MetadataEditor (returns the 'Read Only page if there is no session id)
* Profile (if no session id and no profile id given, displays the No Profile component)
* ProfileEditor (***doesn't handle having no session id, need to fix this*** )
* Profiles (if no session id returns 'Read Only' page)

Before, if we had no session id, then we assumed we were in ReadOnly mode. Is this still a fair assumption? 

EDIT:

Okay, now profile editor will return the 'ReadOnly' page if there is no session id
