### ISSUE TITLE
Table view of data is default (not JSON)

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#309]
Default view on a dataset should be set to table (csv) instead of JSON.
- Thinking is this (rows & columns) is the more conventional/familiar view on data
- column header should freeze (e.g. column header should stay in place as user scrolls down to lower rows
 - column headers should be different color than data held in table (dark fill with light/white text?)
- Perhaps we could eventually build a dropdown tool that allows the data to be displayed in the user's preferred format.

**Comment by b5** [comment]
fixed by now doing the proper thing when we encounter `structure.depth` value of 2 (show a table)
