### ISSUE TITLE
Orientation Page

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#313]
This “page” would answer the question of “how I get started with qri.” 
  - Better answered as a big upgrade to qri.io/docs or a help / FAQ section in the webapp
  - Orientation video(s) 
    - one asciinema for the CLI folks
    - Youtube for the electron

**Comment by rgardaphe** [comment]
"On a dataset after clicking the “Add” button, I don’t know what clicking “delete” will do / means"
    - might be a good chance to introduce pinning terminology

**Comment by ramfox** [comment]
This is a stop-gap for now, but "delete" has been changed to "remove", and after you click to "remove" you get a little blurb saying that you are removing the dataset from your qri node, but if someone else has added it, it might still be available on that node.

**Comment by ramfox** [comment]
we def should still do something like this, but closing for now because it's not on the immediate agenda
