### ISSUE TITLE
Discussion: What do I do with this app?

### ISSUE THREAD

**Issue by ramfox** [qri-io/2017-frontend#315]
This is a long and ongoing discussion, but here are the notes so far:

- Qri app is a place I can discover & get data
- If this is version control, maybe versions should feature more prominently?
- Use the phrase "What do I do with this app?" to guide new features.

**Comment by rgardaphe** [comment]
"Until I can bring my tools to this data, I’m going to be importing/exporting like crazy." This might not be such a bad thing, but we need to focus on integration if so.
  - Explicit documentation on getting data into and out of qri
  - Conversation about data interoperability with adjacent tools (Jupyter Notebook)
  - Embedded Transformations!

**Comment by ramfox** [comment]
closing discussion, we have come a long way since it was started.
