### ISSUE TITLE
Dataset "profile" photo

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#317]
Consider adding ability for users to assign a photo to an individual dataset (like a profile photo, poster photo not necessary at this point).

Why?
 - EPA might run an account, but could want a sub-division's data to be distinguishable from other datasets
  - it's a way to make them fun? It’d be nice if a dataset item was more visually appealing generally, instead of an all-text representation
  - maybe use a taxonomy of glyphs for categories?
  - Could also use the dataset creator’s profile photo as default?

**Comment by ramfox** [comment]
I believe @b5 specifically veto'd pictures for datasets. LMK if I am wrong and I can re-open.
