### ISSUE TITLE
Metadata Changes Summarization Helper

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#332]
Would be nice to be suggested items to comment on when asked to summarize the changes I just made to metadata, e.g.,

Description of changes:

Fields changed:
Language: English   | "Set language to english"
Download Page:      | "Included link to original download page"

Either a text box for each updated field, or just a list of the fields that had been changed (and some basic info on how), and a general text box beneath it to summarize

**Comment by ramfox** [comment]
closing for now, as it's not on the immediate agenda
