### ISSUE TITLE
Dataset duplication bug.

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#333]
I was able to duplicate one of my own datasets by 'adding' it from my home page (after I had uploaded it, of course). Then, when I went to delete one version, qri deleted both.

**Comment by ramfox** [comment]
So you uploaded it, navigated to the dataset page, and then there was an 'add' button for you to click?

**Comment by ramfox** [comment]
After a convo, we believe this bug is actually fixed in the new version. closing for now
