### ISSUE TITLE
Dataset naming & titling at same time

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#334]
I should be able to set the dataset name (in addition to and at the same time i give it a title) upon upload rather than as a metadata change. 

In fact, most fields that are available for me to change under 'metadata' should be available for me to include upon adding the dataset to qri.

This would also save me from having to explain my metadata 'changes' which are really just foundational/time-of-publication pieces of info

**Comment by ramfox** [comment]
titles can only be changed using the editor, and renaming a dataset can no longer happen (for now) on the frontend app. You can, however, go into a dataset, click 'edit', rename the dataset (which creates a new dataset with all the information currently in the editor), which will create a new dataset with the new name.
