### ISSUE TITLE
Grabbable Banner atop qri header.

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#335]
Should keep a banner of dead space atop the app that a user can click to drag the qri app around without worrying about clicking onto 'Back' or another live button.

Suggestion: thin, slightly darker grey banner with Qri metablob logo icon in the top RH corner

**Comment by ramfox** [comment]
So mocked up a quick version of that on sketch, it's in the sketch folder, most recent file.

I'm not sure I love the banner, but I def like having the qri logo in the corner!!

Wondering if maybe it makes more sense for:
1) the banner to be the same color as the background, just in front of everything, that way when the page scrolls up, the buttons/text end up underneath the banner, so you know you can't click it
2) or, and I think this is true of the profile page at minimum anyway, the pages should be static, and only portions of it can scroll, that way no buttons or text will ever be under the banner.

**Comment by ramfox** [comment]
new browser-like format solves this issue. closing.
