### ISSUE TITLE
"Draft Mode" for minor data edits

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#340]
Build a draft mode / page to allow user to clean / munge / fix byte-level data prior to "publication," but after upload to qri. 

Users may prefer that some edits (misspellings) not exist as a publicly-viewable and permanent transformation. 

May want this to only exist BEFORE a dataset is "published" so that all future changes will be tracked.

**Comment by b5** [comment]
I think... we... kinda... made this? That's sorta what the "dry run" feature in the editor does now. Agreed?

**Comment by rgardaphe** [comment]
Wow, yes. I believe so.

**Comment by b5** [comment]
lovely! closing
