### ISSUE TITLE
same dataset showing up multiple times in datasets view after adding title--is that intentional?

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#344]
- I added a dataset with no metadata
- then edited metadata including adding a title
- made a commit
- now see both the original unnamed initial commit AND the latest commit

- Does this mean that we are showing the full commit history in the datasets view?
![image](https://user-images.githubusercontent.com/3967296/40391075-2fc3ebee-5de5-11e8-8017-b391ca5968bc.png)

**Comment by ramfox** [comment]
Hmmmm. 

We are not showing the full commit history in the datasets view, and having trouble recreating the error.

If you exit and load qri again, do you still see both datasets?

**Comment by osterbit** [comment]
quitting and restarting got rid of the error, so maybe less urgent, will follow-up if I encounter the issue again

**Comment by ramfox** [comment]
Okay, just let me know the conditions if it happens again, and I will keep a look out for the bug in the wild. thanks.
