### ISSUE TITLE
Hidden Rows on Datasets

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#347]
Added a dataset with more than 1,000 rows. The default view on "data" tab is: [100 hidden].

Should not the first 100 rows display by default? If not, it should be clearer that clicking the [100 hidden] will expand the list.  Also, when you click into structure or meta or changes and then back into 'data' it returns to the default display (all data being hidden)

**Comment by TheWorldEndsWithUs** [comment]
I believe this issue is still around. When completing a dataset I am unable to view it without refreshing.
When pressing the buttons nothing shows up.

![Screen Shot](https://user-images.githubusercontent.com/567552/60608562-b7bbd280-9d8d-11e9-8b7d-d54f2eddb566.png)
