### ISSUE TITLE
"viewing a previous version" bug

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#348]
I updated ONLY metadata, and upon returning to the dataset's main page i'm alerted with "You are viewing a previous version of this dataset"

Also (and perhaps relatedly), I no longer have the option to "Edit" metadata (the purple button is gone).

Also, I don't see the 'commit' (the metadata update) in the list of changes.

**Comment by ramfox** [comment]
Are you using 0.0.2? This bug still exists in 0.0.2, but should be fixed in the last pr I pushed.
