### ISSUE TITLE
Function akin to Git Rebase Interactive

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#356]
Would like ability to select a number of commits, and collapse / combine them into one 'super commit' a la Git Rebase Interactive.  

This would reduce clutter and number of 'versions' to sort through as one reviews. I still want to be aware of all changes made to a dataset, but there may only truly be many fewer 'versions' than 'commits.'

**Comment by ramfox** [comment]
v cool, but not on the agenda for the moment. Will reopen when we get there.
