### ISSUE TITLE
auto-update issue

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#357]
- after I update my cli binary to 0.50, was unable to get the qri front end to function.  
- each time quit the qri app and relaunched it
   - it would launch, get hung up, then tell me that it would update to 0.1.0 on exit (without ever updating)

- it is also unclear as to whether the user needs to wait or not following the prompt that there is an update and whether the app has updated or not when you start the app--would be nice if this (or even just the version of the gui and cli) was communicated to to the user on startup in the loading screen or in a welcome message

**Comment by b5** [comment]
We've addressed this by moving a copy of the Qri binary into the electron app. Closing!
