### ISSUE TITLE
Metadata Tables

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#372]
We will likely need the Metadata section to support csv tables and .txt files that interpret (offer specific, human-readable definitions) of column headers for the dataset body.  US Census datasets offer index tables that connect 'body' data in separate metadata csv files.

**Comment by ramfox** [comment]
I'm not totally clear on what this is saying. I think it is saying we need a place to put column name definitions? This happens in the Structure section of a dataset, in the json schema.
