### ISSUE TITLE
discuss high level interface options for displaying history of executed sql queries

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#39]
- a popular ui style for 'interactive computing' interfaces is organizing your queries/steps as a list of  'notebook cells'  
- benefits of this style include being able to scroll through your history of steps and make modifications and rerun a sequence of steps
- notable examples include 
  - entire workflow management
    - [jupyter notebook\/jupyterLab\/jupyterHub](https://jupyter.org/)
    - [Apache Zeppelin](http://zeppelin.apache.org/#what-is-apache-zeppelin)
  - react-based SQL notebooks
     - [franchise.cloud](https://franchise.cloud/)

**Comment by osterbit** [comment]
a couple more thoughts
* I guess something like jupyter introduces 2 containers
  * 'execution cells' as containers for a query
  * 'notebooks' as containers for sequences of related queries/ a progression of queries
* might be worth discussing the feasibility of each independently  

and unrelated: 
* one UI feature I like of franchise.cloud is the 'card view' as an alternative to table view, the value add would probably depend on the type of data but can def see scrubbing through a card as a better way to get an overview of the contents of a table than an actual table for certain tables

**Comment by ramfox** [comment]
Closed due to age and we no longer have query history

* could be useful in future discussion of displaying transformations
