### ISSUE TITLE
Choose Target Browsers

### ISSUE THREAD

**Issue by ramfox** [qri-io/2017-frontend#40]
We need to make an educated guess about what browsers our audience will be using.

**Comment by b5** [comment]
@osterbit & @rgardaphe, it'd be great if we have any info lying around on the types of browsers data-oriented people use. My guess is the usual suspects (chrome), but worth making sure we're not missing support for a browser that lots will need. If none of that information is available, let's go with general browser usage stats, which as of this writing seems to be:

* Chrome - 54.89%
* Safari - 14.88%
* UC Browser - 7.43%
* Firefox - 5.9%
* Opera - 4%
* IE - 3.69%

the bigger question is mobile :/

**Comment by ramfox** [comment]
target browsers are chrome, safari, and firefox. done.
