### ISSUE TITLE
ToS exit link changes nothing in the UI

### ISSUE THREAD

**Issue by machawk1** [qri-io/2017-frontend#403]
On the first-run welcome screen of qri 0.5.2 on macOS 10.14.1 I am given two options with regard to accepting the Terms of Service: `Let's Go!` and `exit`. I chose `exit`, figuring I could relaunch and subsequently select `Let's Go!`. Doing so caused no change in the interface aside from a slight highlight of the link onmouseover. Nothing indicating an error was reported to the DevTools console.

**Comment by b5** [comment]
Ooooh good find. We'll hop to it. Thanks @machawk1!

**Comment by ramfox** [comment]
I have this fixed in dev mode for both electron and the webapp. Attempting to packages the electron app to see if it breaks anything.
