### ISSUE TITLE
Adding support for parentheses in where clause would be helpful

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#42]
the error is handled (prints: eval ParenExpr are not implemented. check docs.qri.io/releases for info
Dismiss) so there may be a stub somewhere but this would be nice so I could write  more complex queries (eg: <code>select ... where A and B or C and D </code> != <code>select ... where (A and B) or (C and D) </code>)

**Comment by b5** [comment]
Moved this to qri-io/dataset_sql
