### ISSUE TITLE
fix(editor): fix bugs that get in the way of using qri

### ISSUE THREAD

**Issue by ramfox** [qri-io/2017-frontend#435]
* [x] removing "body" doesn't work
* [x] saving tabular/csv data removes a row each time you save (#436)
* [x] can't save a viz for some reason
* [x] allow removal of schema (if schema section is empty/deleted), don't add a schema by default.
* [x] row #s too dark in edit mode
* [x] tf print statements don't show up 

Punting on these issues:
* can't recall a tf on the frontend
* dataset name show at top in editor
* if on meta page, and you click edit, you should be directed to the meta page on the editor
* editor should return you to where you left off if you navigate away

**Comment by b5** [comment]
I think the csv-eat-a-row problem deserves it's own issue to make sure we get integration with the backend right, so I've broken it out into #436.

I'm also concerned the "can't save a viz for some reason" is _both_ a backend and frontend issue. I've created qri-io/qri#643 to track progress on the backend.
