### ISSUE TITLE
refactor(*): refactor components to look more like plain react

### ISSUE THREAD

**Issue by ramfox** [qri-io/2017-frontend#457]
To facilitate quicker onboarding/more github love on the frontend, and to make it easier to move toward modern React, let's refactor our components away from aphrodite and inheriting from a `Base` component.

This also needs to come with a discussion about css!

Edit:
After discussion w/ @b5 we have a plan. This will be separated into 3 prs:
* [x] remove aphrodite
           - flip `template` to normal `render` func
            - remove aphrodite dependency
            - move styles to scss files
                 -- for components in the general `components` folder: move the css to `_site.scss`
                 -- for component specific styling: `_schema.scss`,` _profile.scss`, `_item.scss`, `_form.scss`, `_editor.scss`, `_dataset.scss`, `_chrome.scss`
* [x] adjust classes to not inherit from Base & remove Base class
* [ ] ~refactor class components to be functional components, for those that don't need the life cycle.~ (will be refactored as we progress not all at once)

**Comment by b5** [comment]
SLAMMIN LGTM

**Comment by ramfox** [comment]
closed by #473
