### ISSUE TITLE
unable to move window, found another app that might have fix

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#50]
another atom app, [hyper](https://github.com/zeit/hyper), also gets rid of the menu bar but allows draggability.  maybe this is helpful/maybe not: from a quick 2 second look at https://github.com/zeit/hyper/blob/master/app/ui/window.js it looks like they have this setting:
 <code>titleBarStyle: 'hidden-inset',</code>

**Comment by b5** [comment]
Should be fixed by #60
