### ISSUE TITLE
UX: how do I get the data?

### ISSUE THREAD

**Issue by Frijol** [qri-io/2017-frontend#501]
From the [overview page](https://app.qri.io/b5/texas_tceq_deer_park_auto_gc) of a dataset, it's not obvious what to do to access the data. "Body" feels like an ambiguous term.

### Suggested fix:

Ideally, there would be a "get data" button somewhere obvious like:

![Screen Shot 2019-06-07 at 1 03 39 PM](https://user-images.githubusercontent.com/454690/59130665-ed9f9f80-8924-11e9-9007-38b0c48bbf21.png)

And if you clicked on it, it would:
1. Check if you had the QRI app
1. Prompt you to install it if you don't have it
1. Open the app to the dataset page
1. Add the dataset to your datasets in the app
1. Maybe even download?

Short of that, it might instead:
* Show you a page in the docs with lots of screen shots working you through that process
* Just tab you over to the "Body" tab

It might also be useful to rename the "Body" tab (and possibly other tabs as well?) to be more descriptive. Alt text on tab names might be another useful clarifying feature.

**Comment by ramfox** [comment]
yes! for app.qri.io we should definitely have this!

Proposed change for right now: a banner that lives above every page that has a button to download the qri desktop app & describes how to get the data w/ link to tutorial
