### ISSUE TITLE
charting feature: univariate distribution plot

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#75]
- only input is a single numeric column
- outputs a point distribution histogram and/or density curve 
- if there is not already a pre-built in function to do this:
  - bin size can be automatically determined using [freedman-diaconis rule](https://en.wikipedia.org/wiki/Freedman%E2%80%93Diaconis_rule)
  - popular python implementation of distplot: https://seaborn.pydata.org/generated/seaborn.distplot.html#seaborn.distplot

**Comment by ramfox** [comment]
Closed due to age and we no longer display charts/graphs
