### ISSUE TITLE
table interaction - cell and cell range selection with mouse and keyboard

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#82]
* [Tad data viewer](http://tadviewer.com/) is the best non-excel example I've come across/is a good point of reference for table interaction that feels smooth
* from a brief look at the [adazzle/react-data-grid](https://github.com/adazzle/react-data-grid) repo and documentation it is not clear to me whether it supports an 'active/selected range of cells' as a component
    * the closest of their examples is a [cell drag down example](http://adazzle.github.io/react-data-grid/examples.html#/cell-drag-down) which differers from the behavior we'd ideally want (but can perhaps be overriden?) in the following ways:
        * range selection appears to be restricted to a single column 
        * it copies the value from the first cell to the range of cells selected instead of just selecting them
        * it uses a handle on the bottom right corner of the cell to trigger the selection rather than the cell itself

**Comment by ramfox** [comment]
HandsonTable solves this problem! You can select multiple columns and rows and copy/paste from it.
