### ISSUE TITLE
have to retype the query each time from scratch whenever I go look something up

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#93]
when I leave the editor to go look up a field name, I find the editor is cleared.

Also kinda related, it would be nice if I didn't have to leave the editor to check what fields are in a table or what the table name is etc

**Comment by ramfox** [comment]
Seems like editor doesn't clear any more. If someone can recreate let me know!

**Comment by ramfox** [comment]
We no longer have a sql editor, closing this issue
